site_name: Rex's Construct 3 plugins
theme: 'material'

pages:
- Home: index.md
- Categories:
  - System:
    - Pause/resume: rex_pause.md
    - Comment: rex_comment.md
  - Data structure:
    - CSV:
      - 2D tables: rex_csv.md
      - CSV to official array object: rex_csv2array.md
    - JSON:
      - JSON plugin: rex_hash.md
      - JSON behavior: rex_bhash.md
  - Logic:
    - Finite state machine:
      - FSM plugin: rex_gfsm.md
      - FSM behavior: rex_fsm.md
    - Invoke Javascript function: rex_jsshell.md
  - Date & time:
    - Javascript built-in date object: rex_date.md
  - Timer:
    - Timeline:  rex_timeline.md
  - Text:
    - Behavior:
      - Scrolling: rex_text_scrolling.md
  - Movement behaviors:
    - Position:
      - Move to: rex_moveto.md
      - Clamp or wrap: rex_boundary.md
      - Push out solid: rex_pushoutsolid.md
    - Angle:
      - Rotate to: rex_rotateto.md
    - Platformer:
      - Move to: rex_platform_moveto.md
    - AI:
      - Boids: rex_boids.md
  - Input:
    - Touch wrap: rex_touchwrap.md
    - Button: rex_button.md
  - Board:
    - Core:
      - Board: rex_board.md
      - SquareTx: rex_board_squaretx.md
      - HexTx: rex_board_hextx.md
  - Backend:
    - Newgrounds.io:
      - Authentication: rex_ngio_authentication.md
      - Scoreboard: rex_ngio_scoreboard.md
      - Medal: rex_ngio_medal.md
      - Gateway: rex_ngio_gateway.md
      - Get url of page: rex_ngio_loader.md
      - Log events: rex_ngio_event.md
- Deprecated:
  - Nickname plugin: rex_nickname.md
  - Nickname behavior: rex_bnickname.md
- Lists: 
  - All plugins: list.index.md
  - Board: board.index.md
  - Newgrounds.io: ngio.index.md


extra_javascript:
- js/mermaid/mermaid.min.js
- js/umlconvert.js 

use_directory_urls: false
google_analytics: ['UA-97103262-1', 'rexrainbow.github.io/C3RexDoc/plugins.md']
    
markdown_extensions:
- admonition
- codehilite(guess_lang=false,linenums=false)
- toc(permalink=true)
- footnotes
- meta
- def_list
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences: [
       {name: mermaid, class: mermaid}
    ]
- pymdownx.tasklist
- pymdownx.tilde